/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import Controlador.*;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class JFrame extends javax.swing.JFrame {
    
    public static Jinete jinete;
    
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        
       
        
        initComponents();
        
        iniSeLabel.setVisible(false);
        aceptarBoton.setVisible(false);
        usuLabel.setVisible(false);
        contraLabel.setVisible(false);
        usuarioText.setVisible(false);
        contrasenia.setVisible(false);
        
        VisualizarBoton.setEnabled(false);
        acercaDeBoton.setEnabled(false);
        abrirConexion.setEnabled(true);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            
        }
    });
        
    }

    public void actualizarPanel(javax.swing.JPanel panel)
    {
        this.setContentPane(panel);
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        iniSeLabel = new javax.swing.JLabel();
        usuLabel = new javax.swing.JLabel();
        contraLabel = new javax.swing.JLabel();
        contrasenia = new javax.swing.JTextField();
        usuarioText = new javax.swing.JTextField();
        aceptarBoton = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        conexionBoton = new javax.swing.JMenu();
        abrirConexion = new javax.swing.JMenuItem();
        cerrarConexion = new javax.swing.JMenuItem();
        VisualizarBoton = new javax.swing.JMenu();
        consultaResumen = new javax.swing.JMenuItem();
        consultaDetalle = new javax.swing.JMenuItem();
        acercaDeBoton = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniSeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        iniSeLabel.setText("Inicio de Sesion");

        usuLabel.setText("Usuario");

        contraLabel.setText("Contraseña");

        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });

        aceptarBoton.setText("Aceptar");
        aceptarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contraLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuarioText)
                            .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(iniSeLabel)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aceptarBoton)
                .addGap(141, 141, 141))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(iniSeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contraLabel))
                .addGap(29, 29, 29)
                .addComponent(aceptarBoton)
                .addGap(27, 27, 27))
        );

        conexionBoton.setText("Conexion");

        abrirConexion.setText("Abrir");
        abrirConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirConexionMouseClicked(evt);
            }
        });
        abrirConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirConexionActionPerformed(evt);
            }
        });
        conexionBoton.add(abrirConexion);

        cerrarConexion.setText("Cerrar");
        cerrarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarConexionActionPerformed(evt);
            }
        });
        conexionBoton.add(cerrarConexion);

        jMenuBar3.add(conexionBoton);

        VisualizarBoton.setText("Visualizar");

        consultaResumen.setText("Resumen");
        consultaResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaResumenActionPerformed(evt);
            }
        });
        VisualizarBoton.add(consultaResumen);

        consultaDetalle.setText("Detalles");
        consultaDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDetalleActionPerformed(evt);
            }
        });
        VisualizarBoton.add(consultaDetalle);

        jMenuBar3.add(VisualizarBoton);

        acercaDeBoton.setText("Acerca de");
        acercaDeBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaDeBotonMouseClicked(evt);
            }
        });
        acercaDeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeBotonActionPerformed(evt);
            }
        });
        jMenuBar3.add(acercaDeBoton);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirConexionMouseClicked
        
        
    }//GEN-LAST:event_abrirConexionMouseClicked

    private void abrirConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirConexionActionPerformed
        Conexion.open();
       
        
        iniSeLabel.setVisible(true);
        aceptarBoton.setVisible(true);
        usuLabel.setVisible(true);
        contraLabel.setVisible(true);
        usuarioText.setVisible(true);
        contrasenia.setVisible(true);
        cerrarConexion.setVisible(true);
        
    }//GEN-LAST:event_abrirConexionActionPerformed

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextActionPerformed

    private void aceptarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarBotonMouseClicked
             
        String usuario = usuarioText.getText();
        String contraseña = contrasenia.getText();
        
        jinete = JineteBD.getJinete(usuario, contraseña);
        
        if(jinete != null){
            JOptionPane.showMessageDialog(rootPane, "Conectado");
            Resumen res = new Resumen(jinete);
        actualizarPanel(res);
        VisualizarBoton.setEnabled(true);
        acercaDeBoton.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Datos incorrectos");
        }
        
        
        
    }//GEN-LAST:event_aceptarBotonMouseClicked

    private void cerrarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarConexionActionPerformed
       Conexion.close();
       
       
       
        iniSeLabel.setVisible(false);
        aceptarBoton.setVisible(false);
        usuLabel.setVisible(false);
        contraLabel.setVisible(false);
        usuarioText.setVisible(false);
        contrasenia.setVisible(false);
        
        JOptionPane.showMessageDialog(rootPane, "Has cerrado la conexion");
        
    }//GEN-LAST:event_cerrarConexionActionPerformed

    private void consultaDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDetalleActionPerformed
       Detalles de = new Detalles(jinete);
       actualizarPanel(de);// TODO add your handling code here:
       
    }//GEN-LAST:event_consultaDetalleActionPerformed

    private void consultaResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaResumenActionPerformed
       Resumen re = new Resumen(jinete);
       actualizarPanel(re);
       CaballoDB.cerrar();
       JineteBD.cerrar();
    }//GEN-LAST:event_consultaResumenActionPerformed

    private void acercaDeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeBotonActionPerformed
      
    }//GEN-LAST:event_acercaDeBotonActionPerformed

    private void acercaDeBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaDeBotonMouseClicked
       AcercaDe ac = new AcercaDe();
       actualizarPanel(ac);
    }//GEN-LAST:event_acercaDeBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu VisualizarBoton;
    private javax.swing.JMenuItem abrirConexion;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JMenu acercaDeBoton;
    private javax.swing.JMenuItem cerrarConexion;
    private javax.swing.JMenu conexionBoton;
    private javax.swing.JMenuItem consultaDetalle;
    private javax.swing.JMenuItem consultaResumen;
    private javax.swing.JLabel contraLabel;
    private javax.swing.JTextField contrasenia;
    private javax.swing.JLabel iniSeLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel usuLabel;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
